"""
LINE Family Bot — Centralized configuration.
"""

from shared.config import env

LINE_CHANNEL_ACCESS_TOKEN = env("LINE_CHANNEL_ACCESS_TOKEN", "")
LINE_CHANNEL_SECRET = env("LINE_CHANNEL_SECRET", "")
LINE_GROUP_ID = env("LINE_GROUP_ID", "")

# Validate required env vars at startup
_MISSING = [k for k, v in {
    "LINE_CHANNEL_ACCESS_TOKEN": LINE_CHANNEL_ACCESS_TOKEN,
    "LINE_CHANNEL_SECRET": LINE_CHANNEL_SECRET,
}.items() if not v]
if _MISSING:
    raise RuntimeError(f"Missing required env vars: {', '.join(_MISSING)}")

GEMINI_API_KEY = env("GEMINI_API_KEY", "")
GROQ_API_KEY = env("GROQ_API_KEY", "")
TMDB_KEY = env("TMDB_API_KEY", "")
NASA_API_KEY = env("NASA_API_KEY", "")
APININJAS_KEY = env("APININJAS_KEY", "")
RAPIDAPI_KEY = env("RAPIDAPI_KEY", "")

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = env("GOOGLE_CLIENT_SECRET", "")
GOOGLE_REFRESH_TOKEN = env("GOOGLE_REFRESH_TOKEN", "")
GOOGLE_CREDENTIALS_JSON = env("GOOGLE_CREDENTIALS_JSON", "")

FAMILY_SHEET_ID = env("FAMILY_SHEET_ID", "")
POINTS_THRESHOLD = int(env("POINTS_THRESHOLD", "5"))
CRON_SECRET = env("CRON_SECRET", "")

LOCATION_LAT = env("LOCATION_LAT", "25.04")
LOCATION_LON = env("LOCATION_LON", "121.53")
WEATHER_CITY = env("WEATHER_CITY", "Taipei")
RENDER_EXTERNAL_URL = env("RENDER_EXTERNAL_URL", "")
